package com.ml.entity;

public enum Disease {
	YELLOW_FEVER, VERTIGO, ECZEMA, UTI, THYROID, COUGH, COLD, FEVER, ULCER, DIABETES, TUBERCULOSIS, TOOTHACHE, TONSILLITIS,
	THYROID_CANCER, THREADWORMS, THIRST, SYPHILIS, SUNBURN, SIDS, STRESS, ANXIETY, DEPRESSION, ABDOMINAL_PAIN, STILL_BIRTH,
	SLEEP_PROBLEMS, SORE_THROAT, SKIN_RASHES, SICKLE_CELL_ANAEMIA, SEPTIC_SHOCK, SCARLET_FEVER, SCHIZOPHRENIA, SCABIES, RABIES,
	RING_WORM, FUNGAL_INFECTION, ARTHRITIS, PSYCHOSIS, PROSTATE_CANCER, PREGNANCY, POSTNATAL_DEPRESSION, OVARY_SYNDROME, PNEUMONIA,
	PERSONALITY_DISORDER, PARKINSONS_DISEASE, PANIC_DISORDER, PANCEATIC_CANCER, OVARIAN_CYCT, OSTEOSARCOMA, OSTEOPOROSIS, OSTEOMYLITIS,
	OESOPHAGAL_CANCER, OCD, OBSESSIVE_CUMPULSIVE_DISORDER, OBESITY;
    }
